version: "3.3"
services:
  qdrant:
    image: qdrant/qdrant:gpu-nvidia-latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant:/qdrant/storage:z
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
