[tool.black]
line-length = 79
preview = true

[tool.mypy]
ignore_missing_imports = true

[tool.poetry]
name = "abstract2gene"
version = "0.1.0"
description = "Word distributions related to gene symbols"
license = "MIT"
authors = [
    "David Connell <davidconnell12@gmail.com>",
]
packages = [
    { include = "abstract2gene" },
]

[tool.poetry.dependencies]
pubnet = "^0.5"
pandas = "^1.4"
nltk = "^3.7"
requests = "^2.28"
python = "~3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
