[tool.black]
line-length = 79
preview = true

[tool.mypy]
ignore_missing_imports = true

[tool.poetry]
name = "abstract2gene"
version = "0.1.0"
description = "Word distributions related to gene symbols"
license = "MIT"
repository = "https://gitlab.com/net-synergy/abstract2gene"
authors = ["David Connell <davidconnell12@gmail.com>"]
packages = [{ include = "abstract2gene" }]

[tool.poetry.dependencies]
python = "^3.8"
pubnet = "^0.6.2"
pandas = "^1.4"
nltk = "^3.7"
requests = "^2.28"
appdirs = "^1.4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
