version: "3.3"
services:
  abstract2gene:
    build:
      context: .
      args:
        EXTRA_TYPE: cpu
    ports: "${A2G_PORT:-8080}:8000"
    tty: true
    depends_on:
      - qdrant
    volumes:
      - ${A2G_DATA_HOME}:/root/.local/share/abstract2gene
      - ${HF_CACHE}:/root/.cache/huggingface
      - ./auth:/root/.local/share/auth
      - ./a2g.toml:/app/a2g.toml
    environment:
      - A2G_QDRANT_URL=qdrant
      - A2G_MODE=${A2G_MODE:-run}

  qdrant:
    image: qdrant/qdrant:latest
    environment:
      - QDRANT__STORAGE__PERFORMANCE__ASYNC_SCORER=true
    volumes:
      - ${QDRANT_HOME}/qdrant:/qdrant/storage:z
