name: Package python packages

on:
  - workflow_call

jobs:
  build-packages:
    runs-on: ubuntu-latest
    env:
      python-version: "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"
          enable-cache: true

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}

      - name: Build wheel and sdist
        run: uv build

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: abstract2gene-${{ github.sha }}
          path: dist/*
